# Generated by Django 4.1.2 on 2022-10-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gpa',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
